let notes = {
  whole: '𝅝',
  half: '𝅗𝅥',
  quarter: '𝅘𝅥',
  eighth: '𝅘𝅥𝅮',
  sixteenth: '𝅘𝅥𝅯',
  trebbleClef: '𝄞',
  bassClef: '𝄢',
  quarterNoteRest: '𝄽',
  wholeNoteRest: '𝄻',
  halfNoteRest: '𝄼',
  eighthNoteRest: '𝄾',
  sixteenNoteRest: '𝄿',
  thirthieth: '𝅘𝅥𝅰',
  lines: '𝄚',
  line: '𝄖',
  dieze: '♯',
  bemol: '♭',
  breve: '𝄯',
  becarre: '𝄯',
  c: '𝄴',
  fortieth: '𝅘𝅥𝅱',
}

export default notes
